spring:
  config:
    import:
      - classpath:/yaml/application-prod.yml
      - classpath:/yaml/application-dev.yml
      - classpath:/yaml/application-local.yml
  profiles:
    active: prod # 원하는 프로필 지정(prod, dev, local)

  # 스프링 시큐리티 설정
  security:
    user:
      name: admin
      password: event1234