spring:
  datasource:
    url: jdbc:mysql://localhost:3306/snapevent_03?serverTimezone=Asia/Seoul
    username: ${datasource.username}
    password: ${datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  # 스프링 시큐리티 설정
  security:
    user:
      name: admin
      password: event1234


